// strings in Login and SignUp part
export const LoginSignupString = {
    Welcome : 'Welcome to Sports Center',
    LogIn: 'LogIn',
    SignUp: 'SignUp',
    Name: 'Name',
    Email: 'Email',
    Password: 'Password',
    HaveAccount: 'Already have account?',
    RequireName: 'Name is required',
    RequireEmail: 'Email Address is required',
    RequirePassword: 'Password is required',
    IncorrectInfo: 'Incorrect email address or password',
    Athlete: 'Athlete',
    Admin: 'Administrator',
    Coach: 'Coach',
    Success: 'Success',
    LoginFailed: 'Login Failed!',
    DbDisconnected: 'Database Disconnected'
};

// strings in Questionnaire part
export const QuestionString = {
    AddQuestionnaire: 'Add Questionnaire',
    AddQues: 'Add Question',
    ViewQues: 'View Question',
    ViewAnswer: 'View Question Answers',
    Template1: 'Pre-training',
    Template2: 'Post-training',
    PlzChooseQuestionnaire: 'Please choose Questionnaire:',
    PlzChoose: 'Please Choose:',
    Next: 'Next',
    Team: 'Team',
    User: 'User',
    QuestionType: 'Question Type',
    OptionNumber: 'Option Number',
    Questionnaire: 'Questionnaire',
    Success: 'Success!',
    UpdateSuccess:  'Update question success',
    Submit: 'Submit',
    OK: 'OK',
    Type: 'Type:',
    Question: 'Question:',
    option1: 'option1:',
    option2: 'option2:',
    option3: 'option3:',
    option4: 'option4:',
    option5: 'option5:',
    option6: 'option6:',
    option7: 'option7:',
    option8: 'option8:',

    AddComment: 'Add a Comment:',
    Comment: 'Comment:',
    Answer: 'Answer:',
    TellYourAnswer: 'Please tell your answer here:',
    Check: 'Check',
    Question: 'Question:',
    TeamQuestion: 'Team Question:',
    PersonalQuestion: 'Personal Question:',
    Date: 'Date:',
    Sort: 'Sort',
    SortByType: 'Sort By Type',
    NewToOld: 'NewToOld',
    OldToNew: 'OldToNew',
    Delete: 'Delete',
    Update: 'Update',
    Text: 'Text',
    RadioButton: 'Radio Buttons',
    CheckBox: 'Check Boxes',
    Modify: 'Modify',
    AssignThisQuestionnaireToTeam: 'Assign this Questionnaire to Team',
    AssignThisQuestionnaireToUser: 'Assign this Questionnaire to User',
    WriteDownAnswer: 'write down your answer',

};

// strings in Training Plan part
export const TrainingStrings = {
    AddTrainingToTeam: 'Add Training Plan(team)',
    AddTrainingToAthlete: 'Add Training Plan(athlete)',
    ViewTrainingTeam: 'View TrainingPlan(team)',
    ViewTrainingAthlete: 'View TrainingPlan(athlete)',
    CheckTeamPlan: 'Check Team Plan',
    TeamTrainingPlan: 'Team Training Plan:',
    CheckPersonalPlan: 'Check Personal Plan',
    PersonalTrainingPlan: 'Personal Training Plan:',
    ChooseUser: 'Choose User',
    ChooseTeam: 'Choose Team',
    StartDate: 'StartDate',
    Confirm: 'Confirm',
    Cancel: 'Cancel',
    EndDate: 'EndDate',
    Next: 'Next',
    Submit: 'Submit',
    Bike: 'Bike',
    Swim: 'Swim',
    Run: 'Run',
    Strength: 'Strength',
    Flexibility: 'Flexibility',
    Training: 'Training',
};

// strings in Physical Data part
export const PhysicalDataStrings ={
    AddPhysicalDataTemplate: 'Add Template',
    ViewPhysicalDataTemplate: 'View Template',
    TemplateName: 'Template Name',
    field1: 'field1',
    field2: 'field2',
    field3: 'field3',
    field4: 'field4',
    field5: 'field5',
    field6: 'field6',

    AddPhysicalData: 'Add Physical Data',
    CheckPhysicalData: 'Check Physical Data',
    NewDate: 'New Date:',
    Update: 'Update',
    Delete: 'Delete',
    Modify: 'Modify',
    
    Success: 'Success',
    OK: 'OK',
    AddPhysicalDataSuccess: 'Add Physical Data Successfully',
    ViewPhysicalData: 'View Physical Data', 
    ComparePhysicalData: 'Compare Physical Data',
    ChooseNewDate: 'Choose New Date',
    Confirm: 'Confirm',
    Cancel: 'Cancel',
    Compare: 'Compare',
    Submit: 'Submit',

    sameUser: 'Compare Same User',
    differenntUsers: 'Compare Different User',
    SelectTemplateAndUser: 'Please select Users and Templates:',
    SelectTemplate: 'Please select Template:',
    SelectUser: 'Please select User:',
    template: 'Template',
    User: 'User:',
    User1: 'User1',
    User2: 'User2',
    Next: 'Next'
};

// strings in User Control part
export const UserControlStrings = {
    Athlete: 'Athlete',
    Name: 'Name:',
    Email: 'Email:',
    Team: 'Team:',
    Status: 'Status',
    AddUser: 'Add New User',
    Athlete: 'Athlete',
    Admin: 'Admin',
    Coach: 'Coach',
    UserType: 'User Type',
    Female: 'Female',
    Male: 'Male',
    Gender: 'Gender',
    Grade: 'Grade',
    grade1: 'grade_1',
    grade2: 'grade_2',
    grade3: 'grade_3',
    grade4: 'grade_4',
    grade5: 'grade_5',
    grade6: 'grade_6',
    grade7: 'grade_7',
    grade8: 'grade_8',
    grade9: 'grade_9',
    grade10: 'grade_10',
    grade11: 'grade_11',
    grade12: 'grade_12',
    
    ModifyInfo: 'Modify Users Information',
    Delete: 'Delete',
    Update: 'Update',
    Modify: 'Modify',
    Assign: 'Assign',
    ToTeam: 'ToTeam',
    Sort: 'Sort',
    SortByTeam: 'SortByTeam',
    SortByUserName: 'SortByUserName',
    Status: 'Activate/Deactivate Users',
    UserStatus: 'User Status:',
    Frozen: 'frozen',
    Active: 'active',
    Activate: 'Activate',
    Deactivate: 'Deactivate',
    TeamMembers: 'Modify Team Members',
    Submit: 'Submit',
    Next: 'Next',
};

// strings in Profile part
export const ProfileStrings = {
    Name: 'Name:',
    Email: 'Email:',
    Team: 'Team:',
    UpdateInformation: 'Update Information',
    Logout: 'LogOut',
};

// strings in Alert part

export const AlertStrings = {
    Success: 'Success',
    Error: 'Error!',
    AddQuestionSuccess: 'Add question success',
    AddTemplateSuccess: 'Add Physical Data Template success',
    AddTrainingPlanSuccess: 'Add Training Plan success',
    DoubleCheck: 'Double Check',
    reallyDelete: 'Really Delete It?',
    Cancel: 'Cancel',
    Delete: 'Delete',
    OK: 'OK',
    NoRecord: 'No Record Found',
    oops: 'Oops...',
    frozen: 'Your Account Has Been Frozen.',
    UpdateInfoSuccess: 'Update User Information Success!',
    UpdatePDTemplateSuccess: 'Update Physical Data Template Success!',
    UpdatePDSuccess:'Update Physical Data Success!',
    TemplateNotMatch: 'Template Not Match!',
    ChooseOnlyTwo: 'Please Select Two Data to Compare',
    NotMatch: 'Not Match',
    PasswordNotMatch: 'Password Not Match',
    AssignQuestionnaireSuccess: 'Assign Questionnaire success',
    AddTrainingPlanSuccess: 'Add Training Plan success',
    SelectTwoDatesPlz: 'Select TWO dates please',
    SubmitQuestionnareSuccess: 'Submit Questionnaire Success',
    ChangeTeamSuccess: 'Change Team Success',


};

// strings in src/components/Routes.hs
export const Routes = {
    Login: 'Login',
    Register: 'Register',
    
}
